baseURL: "https://zlemmon.github.io" 
title: Zachary Lemmon
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Patents
          url: patents/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4

params:
    description: "This website hosts Zachary Lemmon's research papers, patents, curriculum vitae, and contact information."
    author: Zachary Lemmon
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","patents","tags"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Zachary H. Lemmon
          subtitle: "I am a computational biologist with over a decade of experience in academic and industry settings. My research focuses on leveraging bioinformatic and multi-omic modeling approaches to understand and exploit the inheritance of complex traits to benefit the human condition. I was a doctoral student of Dr. John Doebley at the University of Wisconsin, and later a post doctoral researcher with Dr. Zach Lippman at Cold Spring Harbor Laboratory. Most recently I spent time developing the genomic prediction program at Inari Agriculture."

          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Patents
              url: patents/
            - name: Tags
              url: tags/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: LinkedIn
          url: https://www.linkedin.com/in/zlemmon-64729251
        - name: Email
          url: mailto:zlemmon@live.com
#        - name: Gmail
#          url: mailto:zlemmon@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=9IeZnSAAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/zlemmon

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Zachary Lemmon"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
